### ISSUE TITLE
How to get multiple validation errors with line numbers?

### ISSUE THREAD

**Issue by renkei** [jameslan/libxml2-wasm#19]
First of all, great project, thanks  a lot! The runtime plugin approach is always an issue. Either newer Node.js versions are not supported [see #660](https://github.com/libxmljs/libxmljs/issues/660) or there are no updated prebuilt binaries available or the prebuilt binaries are not compatible with the Electron version you want to use, etc. There are many reasons, why this can cause trouble again and again... depending on your environment.

To compile libxml2 to WebAssembly is really a nice idea and solves all issues above. Great!

Now the issue:
When I run the validation, I can see all validation errors as console output of libxml2-wasm, including the line number, but the error I can catch if I put the validate method in a try/catch block as you propose in your example, seems to contain only the last error and only the message without line number.

It would be helpful, if the validator would have a property, let's say `validationErrors` of type `Array<XmlValidateError>` that contains all validationErrors of the last run. XmlValidateError should then have beside property `message` also a property `lineNumber`.

What do you think? Or is there already a possibility to get all errors via API?

**Comment by jameslan** [comment]
Thanks! It make sense that the exception includes line number when the xml content has errors. Will add it a little bit later.

**Comment by ayushmw** [comment]
@jameslan Thank you for making this enhancement. Could you please also publish these changes to [npm](https://www.npmjs.com/package/libxml2-wasm)?

**Comment by jameslan** [comment]
Will release in v0.4.0
