### ISSUE TITLE
DOM manipulation

### ISSUE THREAD

**Issue by jameslan** [jameslan/libxml2-wasm#36]
Implement the following features
- Insert nodes (element, attribute, comment, namespace etc)
- Modify nodes
- Delete nodes

**Comment by ayushmw2** [comment]
Thank you for adding this to your 0.5.0 milestone. We are waiting for this functionality of insert and modify nodes. It would be really helpful if you could let us know by when can we expect this.

**Comment by jameslan** [comment]
@ayushmw2 Thanks for reaching out and showing interest in libxml2-wasm!

Since this project is something we work on in our spare time, it’s tough to lock in a firm release date. Right now, we’re aiming for December, but that’s just an estimate and could change depending on how things go with the development.

We really appreciate your patience!  Thanks again for your support!
