### ISSUE TITLE
Custom XMLInputProvider not working

### ISSUE THREAD

**Issue by tkalmar** [jameslan/libxml2-wasm#58]
I have a custom XMLInputprovider basically mapping URLs to locally cached instances of included xsds:
```
const xmlInputProvider:XmlInputProvider =

{
    match(filename) {
        console.log('Match:', filename);
        let fileName: string;
        const url = URL.canParse(filename);
        if (url){
            fileName = basename(new URL(filename).pathname);
        }
        fileName ??= filename;
        console.log('Loading', fileName,existsSync(`data/${fileName}`));
        return existsSync(`data/${fileName}`);
    },
    close(fd) {
        closeSync(fd);
        return true;
    },
    open(filename) {
        try {
            return openSync(`data/${filename}`, 'r');
        } catch {
            return undefined;
        }
    },
    read(fd, buf) {
        return readSync(fd, buf, 0, buf.byteLength, null);
    },
};
```
It seems to get called and returns the correct contents. But the validation still fails with:
`XmlValidateError: failed to load "http://example.com/some.xsd": No such file or directory.
When i alter the xsd to include from local files, everything works as expected.

**Comment by tkalmar** [comment]
I also tried to use an catalog but this did not help. The catalog works with xmllint cli ...

**Comment by jameslan** [comment]
The parameter used to call `match` and `open` are same.

So if libxml calls `match("http://example.com/some.xsd")`, it will call `open("http://example.com/some.xsd")`.

Please ensure that you also convert the filename in `open`.

**Comment by tkalmar** [comment]
Works like a charm. Thank you!
